"""Curated branch catalog used by the web UI autocomplete."""

BRANCHES = [
    "Adalet",
    "Aile ve Tüketici Hizmetleri",
    "Ayakkabı ve Saraciye Teknolojisi",
    "Beden Eğitimi",
    "Bilgisayar ve Öğretim Teknolojileri",
    "Bilişim Teknolojileri",
    "Biyoloji",
    "Biyomedikal Cihaz Teknolojileri",
    "Büro Yönetimi ve Yönetici Asistanlığı",
    "Coğrafya",
    "Denizcilik",
    "Dilbilim",
    "Din Kültürü ve Ahlak Bilgisi",
    "El Sanatları Teknolojisi",
    "Elektrik-Elektronik Teknolojisi",
    "Endüstriyel Otomasyon Teknolojisi",
    "Felsefe (Felsefe - Mantık - Sosyoloji)",
    "Fen Bilimleri",
    "Fizik",
    "Gazetecilik",
    "Gemi Yapımı",
    "Gıda Teknolojisi",
    "Grafik ve Fotoğraf",
    "Güzellik Hizmetleri",
    "Halkla İlişkiler",
    "Harita-Tapu-Kadastro",
    "Hasta ve Yaşlı Hizmetleri",
    "Havacılık ve Uzay Teknolojisi",
    "Hayvan Yetiştiriciliği ve Sağlığı",
    "Kimya",
    "Kimya Teknolojisi",
    "Konaklama ve Seyahat Hizmetleri",
    "Kuyumculuk Teknolojisi",
    "Laboratuvar Hizmetleri",
    "Maden Teknolojisi",
    "Makine ve Tasarım Teknolojisi",
    "Matbaa Teknolojisi",
    "Matematik",
    "Metal Teknolojisi",
    "Metalürji Teknolojisi",
    "Mikromekanik",
    "Mobilya ve İç Mekân Tasarımı",
    "Moda Tasarım Teknolojileri",
    "Motorlu Araçlar Teknolojisi",
    "Muhasebe ve Finansman",
    "Müzik",
    "Pazarlama ve Perakende",
    "Plastik Sanatlar",
    "Plastik Teknolojisi",
    "Radyo-Televizyon",
    "Raylı Sistemler Teknolojisi",
    "Rehberlik",
    "Sağlık Hizmetleri",
    "Sosyal Bilgiler",
    "Sınıf Öğretmenliği",
    "Tarih",
    "Tarım",
    "Tekstil Teknolojisi",
    "Tesisat Teknolojisi ve İklimlendirme",
    "Türk Dili ve Edebiyatı",
    "Türkçe",
    "Ulaştırma Hizmetleri",
    "Uçak Bakım",
    "Yenilenebilir Enerji Teknolojileri",
    "Yiyecek İçecek Hizmetleri",
    "Çocuk Gelişimi ve Eğitimi",
    "Özel Eğitim",
    "İlköğretim Matematik",
    "İmam-Hatip Lisesi Meslek Dersleri",
    "İnşaat Teknolojisi",
    "İtfaiyecilik ve Yangın Güvenliği",
]
